### ISSUE TITLE
Rebuild Every 6 Hours?

### ISSUE THREAD

**Issue by spslater** [PussTheCat-org/docker-breezewiki-quay#2]
Why does the image get rebuilt every 6 hours when there are no changes to the repository? I use [Diun](https://github.com/crazy-max/diun) to monitor when the Docker images I use are updated, and get a notification every 6 hours, haha.

If it's for something you do with your system, I'm curious to know what that process is.

Thanks

**Comment by TheFrenchGhosty** [comment]
Because CI is free, and because it's always good to have updated dependencies.
