### ISSUE TITLE
How do you hide the "Try our affiliated browser extension" message at the top?

### ISSUE THREAD

**Issue by onlineinternet** [PussTheCat-org/docker-breezewiki-quay#4]
I'm getting "Try our affiliated browser extension - redirect to BreezeWiki automatically!" at the top of every page, but I notice it's not on your instance. How did you remove it?

**Comment by TheFrenchGhosty** [comment]
Looks like it's indeed missing from the official documentation, I just pinged Cadence to add that.

I'll give you the option ASAP.

**Comment by TheFrenchGhosty** [comment]
Okay, so in my case I only want to hide the batter at the top so I use the environment variable:

```
- "bw_promotions::indie_wiki_buddy=home footer"
```

Here's cadence's message from back then (about how to do it in the config.ini file):

![image](https://github.com/PussTheCat-org/docker-breezewiki-quay/assets/47571719/c3f5f101-ed2d-47fd-a68c-60e02af5a96b)
